# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npx
        shell: bash
        run: npm install -g npx

      - name: Install dependencies
        shell: bash
        working-directory: ./email-processor
        run: npm install

      - name: Build TypeScript
        shell: bash
        working-directory: ./email-processor
        run: npx tsc

      - name: Build
        shell: bash
        working-directory: ./email-processor
        run: npm run build

      - name: Test
        shell: bash
        working-directory: ./email-processor
        run: npm run test
